var annotated_dup =
[
    [ "bmi160_acc_any_mot_int_cfg", "structbmi160__acc__any__mot__int__cfg.html", "structbmi160__acc__any__mot__int__cfg" ],
    [ "bmi160_acc_flat_detect_int_cfg", "structbmi160__acc__flat__detect__int__cfg.html", "structbmi160__acc__flat__detect__int__cfg" ],
    [ "bmi160_acc_high_g_int_cfg", "structbmi160__acc__high__g__int__cfg.html", "structbmi160__acc__high__g__int__cfg" ],
    [ "bmi160_acc_low_g_int_cfg", "structbmi160__acc__low__g__int__cfg.html", "structbmi160__acc__low__g__int__cfg" ],
    [ "bmi160_acc_no_motion_int_cfg", "structbmi160__acc__no__motion__int__cfg.html", "structbmi160__acc__no__motion__int__cfg" ],
    [ "bmi160_acc_orient_int_cfg", "structbmi160__acc__orient__int__cfg.html", "structbmi160__acc__orient__int__cfg" ],
    [ "bmi160_acc_sig_mot_int_cfg", "structbmi160__acc__sig__mot__int__cfg.html", "structbmi160__acc__sig__mot__int__cfg" ],
    [ "bmi160_acc_step_detect_int_cfg", "structbmi160__acc__step__detect__int__cfg.html", "structbmi160__acc__step__detect__int__cfg" ],
    [ "bmi160_acc_tap_int_cfg", "structbmi160__acc__tap__int__cfg.html", "structbmi160__acc__tap__int__cfg" ],
    [ "bmi160_aux_cfg", "structbmi160__aux__cfg.html", "structbmi160__aux__cfg" ],
    [ "bmi160_aux_data", "structbmi160__aux__data.html", "structbmi160__aux__data" ],
    [ "bmi160_aux_fifo_data", "structbmi160__aux__fifo__data.html", "structbmi160__aux__fifo__data" ],
    [ "bmi160_cfg", "structbmi160__cfg.html", "structbmi160__cfg" ],
    [ "bmi160_dev", "structbmi160__dev.html", "structbmi160__dev" ],
    [ "bmi160_fifo_frame", "structbmi160__fifo__frame.html", "structbmi160__fifo__frame" ],
    [ "bmi160_foc_conf", "structbmi160__foc__conf.html", "structbmi160__foc__conf" ],
    [ "bmi160_int_pin_settg", "structbmi160__int__pin__settg.html", "structbmi160__int__pin__settg" ],
    [ "bmi160_int_settg", "structbmi160__int__settg.html", "structbmi160__int__settg" ],
    [ "bmi160_int_status", "unionbmi160__int__status.html", "unionbmi160__int__status" ],
    [ "bmi160_int_status_bits", "structbmi160__int__status__bits.html", "structbmi160__int__status__bits" ],
    [ "bmi160_int_type_cfg", "unionbmi160__int__type__cfg.html", "unionbmi160__int__type__cfg" ],
    [ "bmi160_offsets", "structbmi160__offsets.html", "structbmi160__offsets" ],
    [ "bmi160_pmu_status", "structbmi160__pmu__status.html", "structbmi160__pmu__status" ],
    [ "bmi160_sensor_data", "structbmi160__sensor__data.html", "structbmi160__sensor__data" ],
    [ "bmm150_dev", "structbmm150__dev.html", "structbmm150__dev" ],
    [ "bmm150_int_ctrl_settings", "structbmm150__int__ctrl__settings.html", "structbmm150__int__ctrl__settings" ],
    [ "bmm150_mag_data", "structbmm150__mag__data.html", "structbmm150__mag__data" ],
    [ "bmm150_raw_mag_data", "structbmm150__raw__mag__data.html", "structbmm150__raw__mag__data" ],
    [ "bmm150_settings", "structbmm150__settings.html", "structbmm150__settings" ],
    [ "bmm150_trim_registers", "structbmm150__trim__registers.html", "structbmm150__trim__registers" ],
    [ "characteristics", "structcharacteristics.html", "structcharacteristics" ],
    [ "complex", "structcomplex.html", "structcomplex" ],
    [ "NotifyCharacteristics", "struct_notify_characteristics.html", "struct_notify_characteristics" ],
    [ "OPT3001_Config", "union_o_p_t3001___config.html", "union_o_p_t3001___config" ],
    [ "OPT3001_Result", "union_o_p_t3001___result.html", "union_o_p_t3001___result" ]
];